### ISSUE TITLE
Problem mit Timber Plantation Mod

### ISSUE THREAD

**Issue by n00bsy** [braeven/FS22_A_ProductionRevamp#11]
Hallo,

es ist leider nicht möglich bei dem Mod Holzplantage [https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=255170&title=fs2022](url) und Revamp.
Der Mod funktioniert auch so weit was die Produktion betrifft, leider kann man aber nicht auslagern oder verteilen.
folgende Fehlermeldung erhält man egal mit welchen Mods oder Karten man es veruscht.
D:/Dokumente/My Games/FarmingSimulator2022/mods - tests/FS22_A_ProductionRevamp/scripts/revamp_spawner.lua:408: attempt to index field 'productionPoint' (a nil value)
anbei auch eine Log mit nur sehr wenigen Mods als Test
[log.txt](https://github.com/braeven/FS22_A_ProductionRevamp/files/12565516/log.txt)
Es wäre super nett von euch mal das Problem anzusehen.
Besten Dank
n00bsy

**Comment by braeven** [comment]
Ist im nächsten Update behoben.

**Comment by n00bsy** [comment]
> Ist im nächsten Update behoben.

Vielen Dank für die prompte Hilfe, habt einen "alten" Mann ein paar graue Haare erspart! :)
Dankeschön!
