### ISSUE TITLE
Tree saplings

### ISSUE THREAD

**Issue by KalifZerich** [braeven/FS22_A_ProductionRevamp#14]
Hi, it's great that thanks to Revamp I can choose which trees I want in the seedlings, unfortunately no matter what I choose, Spruce always grows, is it possible to solve this somehow? If not, don't mind, I'll keep buying them. I used the ProductionRevamp Productions mod from the modhub where you can grow seedlings in the greenhouse, if possible I would appreciate any help, thanks.

https://www.farming-simulator.com/mod.php?lang=en&country=cz&mod_id=243667&title=fs2022

**Comment by braeven** [comment]
Need to look into that problem, don't know if it is revamp or mod related

**Comment by braeven** [comment]
Looks like I need to change something, will be fixed in the next major version

**Comment by KalifZerich** [comment]
Thank you so much!

**Comment by braeven** [comment]
fixed with version 1.5
