### ISSUE TITLE
Error in  log:    revamp_recipeDisplay.lua:786: bad argument #1 to 'insert' (table expected, got function)

### ISSUE THREAD

**Issue by Lokhorst95** [braeven/FS22_A_ProductionRevamp#15]
[log.txt](https://github.com/braeven/FS22_A_ProductionRevamp/files/13539849/log.txt)

**Comment by braeven** [comment]
Der Bug kommt von Pump and Hoses DLC, die nach dem letzten Patch ein Update noch brauchen. Können wir leider nicht für und tritt auch ohne Revamp auf

This Bug comes from the Pump and Hoses DLC, PnH needs an update after the last patch. Will also apear without revamp sadly

**Comment by Lokhorst95** [comment]
Thanks for your quick reply.

We'll have to wait then :)
