### ISSUE TITLE
Autosold outputs of Productions bleed income when the game is loaded from savegame

### ISSUE THREAD

**Issue by Shad0wlife** [braeven/FS22_A_ProductionRevamp#18]
This is a basegame bug, but I think this is the right mod to fix it.

`ProductionPoint:saveToXMLFile` and `ProductionPoint:loadFromXMLFile` save and load `productionCostsToClaim` from the savegame XML, so running costs that will be paid at the end of the hour get saved when saving mid hour.

But the `soldFillTypesToPayOut` table that contains all "sold" products that are "force-sold" (cannot be stored, eg. the Electricity output of the Straw Harvest Pack's Heat Plant) just gets lost.

These `soldFillTypesToPayOut` only get paid out when `ProductionPoint:updateBalaceDirectlySoldOutputs` is called and that only happens on the full hour in `ProductionChainManager:update` when `if self.hourChangeUpdating`.

This means that (on that production building) if I save and quit and reload at 59minutes of an hour, and have 1 day months, I will lose 0.35 * 600 * EconomyMultiplier = from 210 up to 630 Money.
This should also apply to BGAs (at least from the base game, they "sellDirectly" Electricity and Methane), which pay out way more than the little heat plant.

**Comment by braeven** [comment]
need to test this, but looks good

**Comment by braeven** [comment]
merged with version 1.5.0.2
