### ISSUE TITLE
Error: Running LUA method 'loadSharedI3DFileAsyncFinished'.

### ISSUE THREAD

**Issue by UnknwnArtst** [braeven/FS22_A_ProductionRevamp#24]
Beim Laden von Maps (Standart wie Mod-Maps) wird die Karte nur bis 85% geladen und dann dieser Fehler in der Log eingetragen.

**Error: Folder/FS22_A_ProductionRevamp/scripts/revamp.lua:1936: attempt to compare nil with number**

REvamp Version 1.5.0.3

mit einer älteren Version (1.4.2.0) laden die Karten vollständig. Allerdings wird mir hier ein anderer Error generiert

**Error: Failed to open xml file 'D:/Eigene Dateien/My Games/FarmingSimulator2022/mods/FS22_ProductionRevamp/xml/HelpLine.xml'.**

Könnt ihr euch das bitte mal anschauen? Ich würde gerne die aktuellste Version nutzen und kann dies so leider nicht.

**Comment by Achimobil** [comment]
Einmal die vollständige log bitte, danke

**Comment by UnknwnArtst** [comment]
[log.txt](https://github.com/user-attachments/files/17017812/log.txt) Log mit Version 1.4.2.0

[log.txt](https://github.com/user-attachments/files/17017847/log.txt) Log mit der Version aus dem Modhub 1.5.0.4

gleiches Ergebnis wie bei 1.5.0.3 und die Map ist bei  beiden Logs eine Modmap

**Comment by braeven** [comment]
Revamp befinden sich 2x im ModOrdner und die falsche Version wird geladen:
FS22_ProductionRevamp(falsch)
FS22_A_ProductionRevamp(richtig)

deswegen gibt es Fehler

**Comment by UnknwnArtst** [comment]
Oh, das habe ich gar nicht gesehen das die unterschiedlich in der Bezeichnung sind, hab sonst immer nur den Mod aus dem Modhub geladen und seit kurzem hier von github.

Habe jetzt die Modhub Version geladen und es funktioniert.

Danke dir :) Jetzt klappt alles
