### ISSUE TITLE
Manual spawn with opening hours

### ISSUE THREAD

**Issue by KalifZerich** [braeven/FS22_A_ProductionRevamp#3]
Hello, it not work again, today I update your mod and it dont work - simply cant spawn pallets manually with opening hours/others works. THX

**Comment by KalifZerich** [comment]
![fsScreen_2023_05_04_16_14_18](https://user-images.githubusercontent.com/132508316/236234893-4f0be895-da77-4955-b4c4-463acdf081f6.png)
![fsScreen_2023_05_04_16_15_17](https://user-images.githubusercontent.com/132508316/236234900-a07c2bec-a05a-4372-a6cb-925dd4ddaa67.png)

**Comment by braeven** [comment]
I need some more information, like the xml/mod itself that is not working

**Comment by KalifZerich** [comment]
Sorry its my first time I report something, i will send two XML where I find that, its my mods/edits
[kalifzerich_revamp_problem.zip](https://github.com/braeven/FS22_A_ProductionRevamp/files/11400873/kalifzerich_revamp_problem.zip)
I hope it helps, thx for your work

**Comment by braeven** [comment]
Bug was found and fixed, new version is avaible on modhub
