### ISSUE TITLE
Can "Weight of one animal" be added to the "ANIMALS" table?

### ISSUE THREAD

**Issue by vitalii2011** [braeven/FS22_A_ProductionRevamp#7]
![fsScreen_2023_05_30_1](https://github.com/braeven/FS22_A_ProductionRevamp/assets/41552153/fc262fb9-e4d3-433e-a839-1383570772cd)
So that you do not have to carry back one "does not fit" pig: 
![fsScreen_2023_05_30_2](https://github.com/braeven/FS22_A_ProductionRevamp/assets/41552153/f53e1e76-7151-4b7c-8bc1-8dfcdd2da5fa)

**Comment by Achimobil** [comment]
No, because the weight which is made from one animal in the production is dependent on the settings in the production and the production is independent from the pens. Different productions will have different calculations of what will be added.

**Comment by vitalii2011** [comment]
Understood.
