### ISSUE TITLE
[BUG]: Game stuck in error loop

### ISSUE THREAD

**Issue by westor7** [braeven/FS22_A_ProductionRevamp#9]
Hello,

I was trying to build a ?? and after i opened the menu (ESC) then game stucked and the same error looping all the time in console.

I cannot trigger the same error again, its really strange how was that occurred, i really have not any idea.

Log.txt : [log.txt](https://github.com/braeven/FS22_A_ProductionRevamp/files/12208247/log.txt)

- Thanks!

**Comment by Achimobil** [comment]
First of all the FS22_SpeedLimitOverride makes errors, so you should delte it when there is no error free update available.

The your error loop message is
```
2023-07-30 02:23 Error: Running LUA method 'update'.
dataS/scripts/gui/InGameMenuProductionFrame.lua(197) : attempt to index local 'production' (a nil value)
```
This is a normal LS22 basegame error when you place a production and directly open the ESC menu. 
This is nothing revamp can handle or is responsible for.
We can only suggest after placing a new production do not open the menu in the first seconds.
